set(include_args)
foreach(dir IN LISTS INCLUDE_DIRS)
  if(NOT dir STREQUAL "")
    list(APPEND include_args "-I${dir}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${LOG_DIR}")
foreach(case RANGE 0 6)
  execute_process(COMMAND "${CXX}" -std=c++23 -DHAS_STD_LIB=1 "-DPWM_CASE=${case}"
    ${include_args} -fsyntax-only "${SOURCE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${LOG_DIR}/${case}.log" "${output}${error}")
  if(case EQUAL 0)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Portable PWM application control failed: ${error}")
    endif()
  else()
    if(status EQUAL 0 OR NOT error MATCHES "GREVIR_APPLICATION_ALLOCATION_FAILED|Application has resource conflict")
      message(FATAL_ERROR "Portable PWM case ${case} failed unexpectedly: ${error}")
    endif()
  endif()
endforeach()
message(STATUS "Portable PWM application: positive control and six expected rejections passed")
