file(MAKE_DIRECTORY "${LOG_DIR}")
set(include_args)
foreach(dir IN LISTS INCLUDE_DIRS)
  if(NOT dir STREQUAL "")
    list(APPEND include_args "-I${dir}")
  endif()
endforeach()
foreach(case RANGE 0 7)
  execute_process(COMMAND "${CXX}" -std=c++23 ${include_args}
    "-DCASE_ID=${case}" -fsyntax-only "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/case-${case}.log" "${output}${errors}")
  if(case EQUAL 0)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Valid clock mapping failed: ${errors}")
    endif()
  else()
    if(case EQUAL 1 OR case EQUAL 5)
      set(diagnostic GREVIR_TIMER_INVALID_DIVIDER)
    elseif(case EQUAL 2 OR case EQUAL 6)
      set(diagnostic GREVIR_TIMER_UNORDERED_DIVIDERS)
    elseif(case EQUAL 3 OR case EQUAL 7)
      set(diagnostic GREVIR_TIMER_DUPLICATE_SELECTOR)
    else()
      set(diagnostic GREVIR_TIMER_MIXED_SELECTOR_TYPES)
    endif()
    if(NOT result MATCHES "^[1-9][0-9]*$" OR
        NOT errors MATCHES "static assertion failed[^\n]*${diagnostic}")
      message(FATAL_ERROR "Expected ${diagnostic} for case ${case}: ${errors}")
    endif()
  endif()
endforeach()
message(STATUS "Timer clock mappings: 1 valid and 7 expected rejections passed")
