if(COMPILER_ID STREQUAL "MSVC")
  set(flags /nologo /std:c++latest /Zc:__cplusplus /Zs /DHAS_STD_LIB=1)
  set(include_flag /I)
  set(define_flag /D)
else()
  set(flags -std=c++23 -DHAS_STD_LIB=1 -fsyntax-only)
  set(include_flag -I)
  set(define_flag -D)
endif()
set(include_args)
foreach(dir IN LISTS INCLUDE_DIRS)
  if(NOT dir STREQUAL "")
    list(APPEND include_args "${include_flag}${dir}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${LOG_DIR}")
foreach(case RANGE 0 6)
  execute_process(COMMAND "${CXX}" ${flags} "${define_flag}PWM_CASE=${case}"
    ${include_args} "${SOURCE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(WRITE "${LOG_DIR}/${case}.log" "${output}${error}")
  if(case EQUAL 0)
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Portable PWM application control failed: ${error}")
    endif()
  else()
    if(status EQUAL 0 OR NOT "${output}${error}" MATCHES "GREVIR_APPLICATION_ALLOCATION_FAILED|Application has resource conflict")
      message(FATAL_ERROR "Portable PWM case ${case} failed unexpectedly: ${error}")
    endif()
  endif()
endforeach()
message(STATUS "Portable PWM application: positive control and six expected rejections passed")
