file(MAKE_DIRECTORY "${LOG_DIR}")
if(COMPILER_ID STREQUAL "MSVC")
  set(flags /nologo /std:c++latest /Zc:__cplusplus /Zs)
  set(include_flag /I)
  set(define_flag /D)
else()
  set(flags -std=c++23 -fsyntax-only)
  set(include_flag -I)
  set(define_flag -D)
endif()
set(include_args)
foreach(dir IN LISTS INCLUDE_DIRS)
  if(NOT dir STREQUAL "")
    list(APPEND include_args "${include_flag}${dir}")
  endif()
endforeach()
foreach(case RANGE 0 7)
  execute_process(COMMAND "${CXX}" ${flags} ${include_args}
    "${define_flag}CASE_ID=${case}" "${SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/case-${case}.log" "${output}${errors}")
  if(case EQUAL 0)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Valid clock mapping failed: ${errors}")
    endif()
  else()
    if(case EQUAL 1 OR case EQUAL 5)
      set(diagnostic GREVIR_TIMER_INVALID_DIVIDER)
    elseif(case EQUAL 2 OR case EQUAL 6)
      set(diagnostic GREVIR_TIMER_UNORDERED_DIVIDERS)
    elseif(case EQUAL 3 OR case EQUAL 7)
      set(diagnostic GREVIR_TIMER_DUPLICATE_SELECTOR)
    else()
      set(diagnostic GREVIR_TIMER_MIXED_SELECTOR_TYPES)
    endif()
    if(NOT result MATCHES "^[1-9][0-9]*$" OR
        NOT "${output}${errors}" MATCHES "(static assertion failed|static_assert failed)[^\n]*${diagnostic}")
      message(FATAL_ERROR "Expected ${diagnostic} for case ${case}: ${errors}")
    endif()
  endif()
endforeach()
message(STATUS "Timer clock mappings: 1 valid and 7 expected rejections passed")
